# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 5ba47274f9b181bce26a5150a725577f3c336011  # frozen: v3.6.2
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0b19ef1fd6ad680ed7752d6daba883ce1265a6de  # frozen: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: 81f60f1747e32aa0c6af176c2bd0246a94ec3b2c  # frozen: v0.16.7
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle, --max-line-length=88]

  - repo: local
    hooks:
      - id: generate_requirements.py
        name: generate_requirements.py
        language: system
        entry: python tools/generate_requirements.py
        files: "pyproject.toml|requirements/.*\\.txt|tools/generate_requirements.py"

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.11.0 # v1.3.0
    hooks:
      - id: zizmor

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly
