# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0ee178619d696787ca73d210cc191d720868c631 # frozen: v3.9.6
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 65dbdb59d2f2d9c3bdc343c566821ad3319ddaa3 # frozen: v0.16.3
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: 399947374c9564f1d3bf9921c94ff8b71fc15f4e # frozen: v0.21.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle, --max-line-length=88]

  - repo: local
    hooks:
      - id: generate_requirements.py
        name: generate_requirements.py
        language: system
        entry: python tools/generate_requirements.py
        files: "pyproject.toml|requirements/.*\\.txt|tools/generate_requirements.py"

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly
