# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 5ba47274f9b181bce26a5150a725577f3c336011  # frozen: v3.6.2
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 9c89adb347f6b973f4905a4be0051eb2ecf85dea  # frozen: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: b8f2e0437e4c6f92971972e96320de5afb40adc8  # frozen: v0.17.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle, --max-line-length=88]

  - repo: local
    hooks:
      - id: generate_requirements.py
        name: generate_requirements.py
        language: system
        entry: python tools/generate_requirements.py
        files: "pyproject.toml|requirements/.*\\.txt|tools/generate_requirements.py"

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.14.2 # v1.3.0
    hooks:
      - id: zizmor

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly
