name: Feature request
description: Request or suggest a new feature
title: "<Please write a comprehensive title summarizing your request>"
labels: [":pray: Feature request"]

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time request or suggest a feature! Before
      creating a new issue, please make sure to take a few minutes to check the
      issue tracker for similar issues. Please consider reaching out on 
      our [developer discussion forum](https://discuss.scientific-python.org/c/contributor/skimage)
      if your are unsure if this is a good fit for scikit-image.

- type: textarea
  validations:
    required: true
  attributes:
    label: "Proposed new feature or change:"
    description: >
      Please describe your desired feature or new behavior with all necessary
      detail.

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: >
      By submitting this issue, you agree to follow our 
      [Code of Conduct](https://scikit-image.org/docs/stable/conduct/code_of_conduct.html)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
