from . import _api
from ._multimethods import (autolevel, autolevel_percentile, enhance_contrast,
                            enhance_contrast_percentile, entropy, equalize,
                            geometric_mean, gradient, gradient_percentile,
                            majority, maximum, mean, mean_bilateral,
                            mean_percentile, median, minimum, modal,
                            noise_filter, otsu, percentile, pop, pop_bilateral,
                            pop_percentile, subtract_mean,
                            subtract_mean_percentile, sum, sum_bilateral,
                            sum_percentile, threshold, threshold_percentile,
                            windowed_histogram)

__all__ = ['autolevel',
           'autolevel_percentile',
           'gradient',
           'equalize',
           'gradient_percentile',
           'majority',
           'maximum',
           'mean',
           'geometric_mean',
           'mean_percentile',
           'mean_bilateral',
           'subtract_mean',
           'subtract_mean_percentile',
           'median',
           'minimum',
           'modal',
           'enhance_contrast',
           'enhance_contrast_percentile',
           'pop',
           'pop_percentile',
           'pop_bilateral',
           'sum',
           'sum_bilateral',
           'sum_percentile',
           'threshold',
           'threshold_percentile',
           'noise_filter',
           'entropy',
           'otsu',
           'percentile',
           'windowed_histogram']

__3Dfilters = ['autolevel',
               'equalize',
               'gradient',
               'majority',
               'maximum',
               'mean',
               'geometric_mean',
               'subtract_mean',
               'median',
               'minimum',
               'modal',
               'enhance_contrast',
               'pop',
               'sum',
               'threshold',
               'noise_filter',
               'entropy',
               'otsu']