"""Adapt ``_skimage2`` doctest examples for the public ``skimage`` namespace.

Implementation docstrings in ``_skimage2`` use internal imports such as ``from
_skimage2 import data``. `skimage` shims call :func:`adapt_doctests` so
``skimage`` users see and run ``skimage`` examples instead.
:func:`adapt_doctests` never modifies implementation objects from
``_skimage2``; it returns copies (of functions) or sub-classes (of classes),
where docstrings need to be modified.  For the subclasses, the ``__module__``
attribute is the shim path (for pytest doctest collection).

:func:`adapt_doctests` also copies ``__doctest_requires__`` and
``__doctest_skip__`` from ``_skimage2`` implementation modules onto the shim
module so ``pytest-doctestplus`` can skip examples with missing optional
dependencies, and adds ``np`` to the shim module namespace for doctest runners.
"""

from __future__ import annotations

import functools
import inspect
import re
import types
from collections.abc import Mapping

# For namespace injection
import numpy as np  # noqa: F401


__all__ = ['adapt_doctests']

_DOCTEST_PROMPT_RE = re.compile(
    r'''
    ^(?P<indent>\s*)
    (>>> )
    ''',
    flags=re.VERBOSE,
)

# Search / replace pairs.
_SEARCH_REP_PAIRS = (
    (re.compile(r'import _?skimage2 as ski2'), 'import skimage as ski'),
    (re.compile(r'ski2\.'), 'ski.'),
    (
        re.compile(
            r'''
                (?P<fi>from|import)\ +
                (_?skimage2)
                (?P<connect>[ .])''',
            flags=re.VERBOSE,
        ),
        r'\g<fi> skimage\g<connect>',
    ),
    (re.compile(r'_?skimage2\.'), 'skimage.'),
)


def _adapt_doctest_doc(doc: str | None) -> str | None:
    """Rewrite ``_skimage2`` / ``skimage2`` inside doctest blocks only.

    Parameters
    ----------
    doc : str
        Docstring with doctests changed to use `skimage` instead of
        ``_skimage2`` / ``_skimage2``.

    Returns
    -------
    new_doc : str
        Docstring modified to change ``_skimage2`` / ``skimage2`` examples in
        doctests to use ``skimage`` instead.  If `doc` is None or empty, ``doc
        is new_doc``, otherwise `new_doc` is a new string.
    """
    if not doc:
        return doc

    lines: list[str] = doc.split('\n')
    out: list[str] = []

    while lines:
        line = lines.pop(0)
        if not (match := _DOCTEST_PROMPT_RE.match(line)):
            out.append(line)
            continue
        n_block_indent: int = len(match.group('indent'))
        out.append(_proc_line(line))
        in_doctest_block: bool = True

        while in_doctest_block and lines:
            line = lines.pop(0)
            n_indent = len(line) - len(line.lstrip())
            in_doctest_block = line and (n_indent >= n_block_indent)
            out.append(_proc_line(line) if in_doctest_block else line)

    return '\n'.join(out)


def _proc_line(line):
    for regx, subs in _SEARCH_REP_PAIRS:
        line = regx.sub(subs, line)
    return line


def _make_inheritor(old_class, doc, mod_name):
    """Return new class that inherits from `old_class`

    Parameters
    ----------
    old_class: type
        Input class
    doc: str
        Class docstring for new class.
    mod_name: str
        Module name for new class.

    Returns
    -------
    new_class: type
        A class that inherits from `old_class`
    """
    new_class = types.new_class(
        old_class.__name__,
        (old_class,),  # Inherits from original.
        {},
    )
    new_class.__doc__ = doc
    new_class.__module__ = mod_name
    new_class.__qualname__ = old_class.__qualname__
    return new_class


def _adapt_obj_doctest(obj, shim_module: str = None):
    """Return a shim-local view with adapted doctest examples, as necessary

    If a function needs a modified docstring, we return a copy of that
    function.

    If a class needs modified class or method docstrings, we return new class
    that is a subclass of the old, with modified docstrings.

    If no docstring modifications are necessary, or `obj` is neither a function
    nor a class, we return the original object.
    """
    original_doc = getattr(obj, '__doc__', None)
    adapted_doc = _adapt_doctest_doc(original_doc)
    if inspect.isroutine(obj) and original_doc != adapted_doc:
        return _copy_callable(obj, adapted_doc, shim_module)
    if inspect.isclass(obj):
        return _adapt_class(obj, adapted_doc, shim_module)
    return obj


def adapt_doctests(
    ns: Mapping[str, object],
    *,
    skip_names: tuple[str, ...] = (),
) -> None:
    """Adapt docstrings for callables and classes exported from a shim module

    ns : Mapping
        Namespace of shim module.  Usually generated by passing result of
        ``globals()`` from within shim module ``__init__``.  `ns` should define
        at least the ``__name__`` element.  We modify `ns` in-place.
    skip_names : tuple of str, optional, keyword-only
        Names of objects to pass through without modification.

    Returns
    -------
    None
    """
    if not isinstance(ns, dict):
        raise TypeError('adapt_doctests expects a mutable mapping such as globals()')
    shim_module = ns.get('__name__')
    skip = set(skip_names)
    # Collect implementing modules for functions / classes in namespace.
    # Adapt doctests for functions / classes.
    impl_modules: set[types.ModuleType] = set()
    for name, obj in list(ns.items()):
        if name.startswith('__') or name in skip or inspect.ismodule(obj):
            continue
        if not (inspect.isroutine(obj) or inspect.isclass(obj)):
            continue
        impl_module = inspect.getmodule(obj)
        if impl_module is not None:
            impl_modules.add(impl_module)
        ns[name] = _adapt_obj_doctest(obj, shim_module=shim_module)

    # Apply doctest-plus markers from original implementions.
    if impl_modules:
        _sync_doctest_markers(ns, impl_modules, shim_module)

    module_doc = ns.get('__doc__')
    adapted_module_doc = _adapt_doctest_doc(module_doc)
    if adapted_module_doc != module_doc:
        ns['__doc__'] = adapted_module_doc

    # Add NumPy `np` to module namespace for doctest compatibility.
    ns.setdefault('np', np)


def _sync_doctest_markers(
    ns: dict,
    impl_modules: set[types.ModuleType],
    shim_module: str,
) -> None:
    """Copy pytest-doctestplus skip metadata from implementation modules."""
    requires = dict(ns.get('__doctest_requires__', {}))
    skip = list(ns.get('__doctest_skip__', []))

    for impl_module in impl_modules:
        for key, mods in getattr(impl_module, '__doctest_requires__', {}).items():
            merged = requires.setdefault(key, [])
            merged.extend(m for m in mods if m not in merged)

        for pattern in getattr(impl_module, '__doctest_skip__', []):
            if pattern not in skip:
                skip.append(pattern)

    if requires:
        ns['__doctest_requires__'] = requires
    if skip:
        ns['__doctest_skip__'] = skip


def _copy_callable(obj, adapted_doc, module_name):
    """Make copy of function `obj` with given ``__doc__`` and ``__module__``."""
    new_func = types.FunctionType(
        obj.__code__,
        obj.__globals__,
        obj.__name__,
        obj.__defaults__,
        obj.__closure__,
    )
    functools.update_wrapper(new_func, obj)
    new_func.__kwdefaults__ = obj.__kwdefaults__
    new_func.__doc__ = adapted_doc
    new_func.__module__ = module_name
    return new_func


def _adapt_class(old_class, class_doc, mod_name):
    """Return new inherited class if docstrings adapted else `old_class`

    If `class_doc` differs from ``__doc__`` for `old_class` or any of the
    methods of `old_class` need docstring modifications, return ``new_class``
    that inherits from `old_class`, and that has modified docstrings. Otherwise
    return unmodified `old_class`.

    Only directly-defined members of `old_class` (not inherited ones) are
    inspected.  When a method's ``__doc__`` contains ``_skimage2`` /
    ``skimage2`` references that the doctest adapters would rewrite, a copy
    with the adapted docstring is set on `new_class`.  The original class and
    its methods are never mutated.

    Parameters
    ----------
    old_class : type
    class_doc : str or None
        Desired docstring for output class.
    mod_name : str
        Module name for any new class.

    Returns
    -------
    out : type
        If docstrings need modification for `old_class`, return ``new_class``
        that inherits from `old_class`, but with modified docstrings, and
        `mod_name` set to ``out.__module__``.  Otherwise return `old_class`.
    """
    out = old_class
    if class_doc != getattr(old_class, '__doc__', None):
        out = _make_inheritor(old_class, class_doc, mod_name)
    for name, member in vars(old_class).items():
        if name.startswith('__') and name != '__init__':
            continue

        if isinstance(member, (staticmethod, classmethod)):
            unwrapped = member.__func__
        elif inspect.isroutine(member):
            unwrapped = member
        else:  # Not a (class-, static-, ordinary-) method.
            continue

        original_doc = getattr(unwrapped, '__doc__', None)
        if not original_doc:
            continue

        adapted_doc = _adapt_doctest_doc(original_doc)
        if adapted_doc == original_doc:
            continue

        if out is old_class:  # Now we must modify.
            out = _make_inheritor(old_class, class_doc, mod_name)
        new_func = _copy_callable(unwrapped, adapted_doc, mod_name)
        if isinstance(member, (staticmethod, classmethod)):
            new_func = type(member)(new_func)
        setattr(out, name, new_func)

    return out
