from _skimage2.color.rgb_colors import (
    aliceblue as aliceblue,
    antiquewhite as antiquewhite,
    aqua as aqua,
    aquamarine as aquamarine,
    azure as azure,
    beige as beige,
    bisque as bisque,
    black as black,
    blanchedalmond as blanchedalmond,
    blue as blue,
    blueviolet as blueviolet,
    brown as brown,
    burlywood as burlywood,
    cadetblue as cadetblue,
    chartreuse as chartreuse,
    chocolate as chocolate,
    coral as coral,
    cornflowerblue as cornflowerblue,
    cornsilk as cornsilk,
    crimson as crimson,
    cyan as cyan,
    darkblue as darkblue,
    darkcyan as darkcyan,
    darkgoldenrod as darkgoldenrod,
    darkgray as darkgray,
    darkgreen as darkgreen,
    darkgrey as darkgrey,
    darkkhaki as darkkhaki,
    darkmagenta as darkmagenta,
    darkolivegreen as darkolivegreen,
    darkorange as darkorange,
    darkorchid as darkorchid,
    darkred as darkred,
    darksalmon as darksalmon,
    darkseagreen as darkseagreen,
    darkslateblue as darkslateblue,
    darkslategray as darkslategray,
    darkslategrey as darkslategrey,
    darkturquoise as darkturquoise,
    darkviolet as darkviolet,
    deeppink as deeppink,
    deepskyblue as deepskyblue,
    dimgray as dimgray,
    dimgrey as dimgrey,
    dodgerblue as dodgerblue,
    firebrick as firebrick,
    floralwhite as floralwhite,
    forestgreen as forestgreen,
    fuchsia as fuchsia,
    gainsboro as gainsboro,
    ghostwhite as ghostwhite,
    gold as gold,
    goldenrod as goldenrod,
    gray as gray,
    green as green,
    greenyellow as greenyellow,
    grey as grey,
    honeydew as honeydew,
    hotpink as hotpink,
    indianred as indianred,
    indigo as indigo,
    ivory as ivory,
    khaki as khaki,
    lavender as lavender,
    lavenderblush as lavenderblush,
    lawngreen as lawngreen,
    lemonchiffon as lemonchiffon,
    lightblue as lightblue,
    lightcoral as lightcoral,
    lightcyan as lightcyan,
    lightgoldenrodyellow as lightgoldenrodyellow,
    lightgray as lightgray,
    lightgreen as lightgreen,
    lightgrey as lightgrey,
    lightpink as lightpink,
    lightsalmon as lightsalmon,
    lightseagreen as lightseagreen,
    lightskyblue as lightskyblue,
    lightslategray as lightslategray,
    lightslategrey as lightslategrey,
    lightsteelblue as lightsteelblue,
    lightyellow as lightyellow,
    lime as lime,
    limegreen as limegreen,
    linen as linen,
    magenta as magenta,
    maroon as maroon,
    mediumaquamarine as mediumaquamarine,
    mediumblue as mediumblue,
    mediumorchid as mediumorchid,
    mediumpurple as mediumpurple,
    mediumseagreen as mediumseagreen,
    mediumslateblue as mediumslateblue,
    mediumspringgreen as mediumspringgreen,
    mediumturquoise as mediumturquoise,
    mediumvioletred as mediumvioletred,
    midnightblue as midnightblue,
    mintcream as mintcream,
    mistyrose as mistyrose,
    moccasin as moccasin,
    navajowhite as navajowhite,
    navy as navy,
    oldlace as oldlace,
    olive as olive,
    olivedrab as olivedrab,
    orange as orange,
    orangered as orangered,
    orchid as orchid,
    palegoldenrod as palegoldenrod,
    palegreen as palegreen,
    palevioletred as palevioletred,
    papayawhip as papayawhip,
    peachpuff as peachpuff,
    peru as peru,
    pink as pink,
    plum as plum,
    powderblue as powderblue,
    purple as purple,
    red as red,
    rosybrown as rosybrown,
    royalblue as royalblue,
    saddlebrown as saddlebrown,
    salmon as salmon,
    sandybrown as sandybrown,
    seagreen as seagreen,
    seashell as seashell,
    sienna as sienna,
    silver as silver,
    skyblue as skyblue,
    slateblue as slateblue,
    slategray as slategray,
    slategrey as slategrey,
    snow as snow,
    springgreen as springgreen,
    steelblue as steelblue,
    tan as tan,
    teal as teal,
    thistle as thistle,
    tomato as tomato,
    turquoise as turquoise,
    violet as violet,
    wheat as wheat,
    white as white,
    whitesmoke as whitesmoke,
    yellow as yellow,
    yellowgreen as yellowgreen,
)  # noqa: F401

__all__ = [
    'aliceblue',
    'antiquewhite',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'black',
    'blanchedalmond',
    'blue',
    'blueviolet',
    'brown',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkgreen',
    'darkgrey',
    'darkkhaki',
    'darkmagenta',
    'darkolivegreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkseagreen',
    'darkslateblue',
    'darkslategray',
    'darkslategrey',
    'darkturquoise',
    'darkviolet',
    'deeppink',
    'deepskyblue',
    'dimgray',
    'dimgrey',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'gold',
    'goldenrod',
    'gray',
    'green',
    'greenyellow',
    'grey',
    'honeydew',
    'hotpink',
    'indianred',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavenderblush',
    'lawngreen',
    'lemonchiffon',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'lightgray',
    'lightgreen',
    'lightgrey',
    'lightpink',
    'lightsalmon',
    'lightseagreen',
    'lightskyblue',
    'lightslategray',
    'lightslategrey',
    'lightsteelblue',
    'lightyellow',
    'lime',
    'limegreen',
    'linen',
    'magenta',
    'maroon',
    'mediumaquamarine',
    'mediumblue',
    'mediumorchid',
    'mediumpurple',
    'mediumseagreen',
    'mediumslateblue',
    'mediumspringgreen',
    'mediumturquoise',
    'mediumvioletred',
    'midnightblue',
    'mintcream',
    'mistyrose',
    'moccasin',
    'navajowhite',
    'navy',
    'oldlace',
    'olive',
    'olivedrab',
    'orange',
    'orangered',
    'orchid',
    'palegoldenrod',
    'palegreen',
    'palevioletred',
    'papayawhip',
    'peachpuff',
    'peru',
    'pink',
    'plum',
    'powderblue',
    'purple',
    'red',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'salmon',
    'sandybrown',
    'seagreen',
    'seashell',
    'sienna',
    'silver',
    'skyblue',
    'slateblue',
    'slategray',
    'slategrey',
    'snow',
    'springgreen',
    'steelblue',
    'tan',
    'teal',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'white',
    'whitesmoke',
    'yellow',
    'yellowgreen',
]

from skimage._doctest_adapters import adapt_doctests

adapt_doctests(globals())
