#!/usr/bin/env python
"""Generate requirements/*.txt files from pyproject.toml.

Also builds a conda environment.yml
"""

import re
from pathlib import Path

import tomllib as toml

script_pth = Path(__file__)
repo_dir = script_pth.parent.parent
script_relpth = script_pth.relative_to(repo_dir)
header = [
    f"# Generated via {script_relpth.as_posix()} and pre-commit hook.",
    "# Do not edit this file; modify pyproject.toml instead.",
]


def generate_requirement_file(name: str, req_list: list[str]) -> None:
    req_fname = repo_dir / "requirements" / f"{name}.txt"
    req_fname.write_text("\n".join(header + req_list) + "\n")


def generate_environment_yml(req_sections: dict[str, list[str]]) -> None:
    # Some packages in conda-forge have different names than they do on pypi
    # Also, some packages have a 'base' flavoured conda package which
    # doesn't install all their optional dependencies.
    rename_idx = {
        'build': 'python-build',
        'kaleido': 'python-kaleido',
        'sphinx_design': 'sphinx-design',
        'astropy': 'astropy-base',
        'matplotlib': 'matplotlib-base',
    }
    # scikit-image-data isn't on conda-forge yet, and even once it is, a
    # direct URL/VCS reference (as used temporarily below) could never be a
    # plain conda dependency line regardless; it must go under `pip:`.
    pip_only = ['docstub', 'scikit-image-data']

    lines = ["name: skimage-dev", "channels:", "  - conda-forge", "dependencies:"]
    pip_section = {None: []}

    def _section_to_lst(
        section: str | None, req_sections: dict[str, list[str]], lines, offset=0
    ):
        tab = offset * " "
        header_added = False
        for dep in req_sections[section]:
            # Remove optional specifiers such as `[parallel]`
            dep = re.sub('\\[.*?\\]', '', dep)

            # Remove platform specifiers such as `; sys_platform != "emscripten"`
            # (PEP 508 requires a space before ";" after a direct URL
            # reference, e.g. "name @ url ; marker", so strip that too).
            dep = re.sub(r'\s*; .*', '', dep)

            # Split on the first version/URL-reference marker (">", "=", "@")
            # or whitespace, so a PEP 508 direct reference like
            # "name @ git+https://..." yields just "name", not the whole
            # string (a plain "pooch>=1.6.0"-style specifier still works,
            # since none of these characters appear before its version).
            pkgname = re.split(r'[>=@\s]', dep)[0]

            if section and pkgname in pip_only:
                if dep not in pip_section[None]:
                    pip_section[None].append(dep)
                continue

            dep = dep.replace(pkgname, rename_idx.get(pkgname, pkgname))
            if dep == "scikit-image":
                continue

            # Only emit the section header once we know it has at least one
            # conda-installable entry; otherwise (e.g. a section made up
            # entirely of pip_only packages) it'd be a dangling comment with
            # nothing under it.
            if section and not header_added:
                lines.append(tab + f"  # {section}")
                header_added = True

            lines.append(tab + f"  - {dep}")

            # Strip duplicates
            if len(lines) > 1 and lines[-2].startswith(tab + "  - "):
                if re.split('[>=]', lines[-2])[0] == re.split('[>=]', lines[-1])[0]:
                    lines.pop()

    for section in req_sections:
        _section_to_lst(section, req_sections, lines)

    if pip_section[None]:
        lines.append('  # pypa-only packages')
        lines.append('  - pip')
        lines.append('  - pip:')
        _section_to_lst(None, pip_section, lines, offset=4)

    with open("environment.yml", "w") as f:
        f.writelines(f"{line}\n" for line in lines)


def expand_dependencies(
    dep_list: list[str],
    optional_dict: dict[str, list[str]],
    package_name: str = 'scikit-image',
) -> list[str]:
    """Explode dependencies with optional extras into a flat list.

    If `scikit-image[optional_group]` is used as a dependency itself, replace
    with the actual dependencies of `optional_group`.
    """
    exploded = []
    for dep in dep_list:
        if dep.startswith(f'{package_name}['):
            extras = dep.split('[')[1].rstrip(']').split(',')
            exploded.extend(
                expand_dependencies(
                    optional_dict[extras[0]], optional_dict, package_name
                )
            )
        else:
            exploded.append(dep)
    return exploded


def main() -> None:
    pyproject = toml.loads((repo_dir / "pyproject.toml").read_text())

    generate_requirement_file("default", pyproject["project"]["dependencies"])

    for key, opt_list in pyproject["project"]["optional-dependencies"].items():
        generate_requirement_file(
            key,
            expand_dependencies(
                opt_list,
                pyproject["project"]["optional-dependencies"],
                package_name='scikit-image',
            ),
        )

    generate_environment_yml(
        {
            **{'base': pyproject["project"]["dependencies"]},
            **pyproject["project"]["optional-dependencies"],
        }
    )


if __name__ == "__main__":
    main()
