from _skimage2.filters.edges import (
    HFARID_WEIGHTS as HFARID_WEIGHTS,
    HPREWITT_WEIGHTS as HPREWITT_WEIGHTS,
    HSCHARR_WEIGHTS as HSCHARR_WEIGHTS,
    HSOBEL_WEIGHTS as HSOBEL_WEIGHTS,
    PREWITT_EDGE as PREWITT_EDGE,
    PREWITT_SMOOTH as PREWITT_SMOOTH,
    ROBERTS_ND_WEIGHTS as ROBERTS_ND_WEIGHTS,
    ROBERTS_PD_WEIGHTS as ROBERTS_PD_WEIGHTS,
    SCHARR_EDGE as SCHARR_EDGE,
    SCHARR_SMOOTH as SCHARR_SMOOTH,
    SOBEL_EDGE as SOBEL_EDGE,
    SOBEL_SMOOTH as SOBEL_SMOOTH,
    VFARID_WEIGHTS as VFARID_WEIGHTS,
    VPREWITT_WEIGHTS as VPREWITT_WEIGHTS,
    VSCHARR_WEIGHTS as VSCHARR_WEIGHTS,
    VSOBEL_WEIGHTS as VSOBEL_WEIGHTS,
    farid as farid,
    farid_edge as farid_edge,
    farid_h as farid_h,
    farid_smooth as farid_smooth,
    farid_v as farid_v,
    laplace as laplace,
    prewitt as prewitt,
    prewitt_h as prewitt_h,
    prewitt_v as prewitt_v,
    roberts as roberts,
    roberts_neg_diag as roberts_neg_diag,
    roberts_pos_diag as roberts_pos_diag,
    scharr as scharr,
    scharr_h as scharr_h,
    scharr_v as scharr_v,
    sobel as sobel,
    sobel_h as sobel_h,
    sobel_v as sobel_v,
)  # noqa: F401

__all__ = [
    'HFARID_WEIGHTS',
    'HPREWITT_WEIGHTS',
    'HSCHARR_WEIGHTS',
    'HSOBEL_WEIGHTS',
    'PREWITT_EDGE',
    'PREWITT_SMOOTH',
    'ROBERTS_ND_WEIGHTS',
    'ROBERTS_PD_WEIGHTS',
    'SCHARR_EDGE',
    'SCHARR_SMOOTH',
    'SOBEL_EDGE',
    'SOBEL_SMOOTH',
    'VFARID_WEIGHTS',
    'VPREWITT_WEIGHTS',
    'VSCHARR_WEIGHTS',
    'VSOBEL_WEIGHTS',
    'farid',
    'farid_edge',
    'farid_h',
    'farid_smooth',
    'farid_v',
    'laplace',
    'prewitt',
    'prewitt_h',
    'prewitt_v',
    'roberts',
    'roberts_neg_diag',
    'roberts_pos_diag',
    'scharr',
    'scharr_h',
    'scharr_v',
    'sobel',
    'sobel_h',
    'sobel_v',
]

from _skimage2.filters.edges import _mask_filter_result  # noqa: F401

from skimage._doctest_adapters import adapt_doctests

adapt_doctests(globals())
