name: Test Linux wheel for a given Python version
on:
  workflow_call:
    inputs:
      OPTIONS_NAME:
        required: true
        type: string
      MINIMUM_REQUIREMENTS:
        required: false
        type: string
        default: 0
      OPTIONAL_DEPS:
        required: false
        type: string
        default: 0
      EAGER_IMPORT:
        required: false
        type: string
        default: 0
      WITHOUT_POOCH:
        required: false
        type: string
        default: 0
      PIP_FLAGS:
        required: false
        type: string
        default: ""
      PYTHONOPTIMIZE:
        required: false
        type: string
        default: 0

jobs:
  test-linux:
    name: linux-cp${{ inputs.python-version }}-${{ inputs.OPTIONS_NAME }}
    runs-on: ubuntu-latest

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false

    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: skimage-linux-${{ inputs.python-version }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          allow-prereleases: true
          cache: "pip"

      - name: Install
        env:
          PIP_FLAGS: ${{ inputs.PIP_FLAGS }}
        run: |
          pip install dist/*.whl

      - name: Install test dependencies
        env:
          MINIMUM_REQUIREMENTS: ${{ inputs.MINIMUM_REQUIREMENTS }}
          OPTIONAL_DEPS: ${{ inputs.OPTIONAL_DEPS }}
          WITHOUT_POOCH: ${{ inputs.WITHOUT_POOCH }}
          PIP_FLAGS: ${{ inputs.PIP_FLAGS }}
        run: |
          source .github/scripts/setup-test-env.sh

      - name: Verify non-conflicting dependencies
        if: ${{ inputs.OPTIONAL_DEPS == 1 && inputs.MINIMUM_REQUIREMENTS == 0 }}
        run: |
          # Attempt to resolve all requirements simultaneously
          pip install --dry-run --ignore-installed $(ls requirements/*.txt | sed 's/^/-r /')

      - name: Run tests
        env:
          # A lazy loader configuration parameter
          EAGER_IMPORT: ${{ inputs.EAGER_IMPORT }}
          MINIMUM_REQUIREMENTS: ${{ inputs.MINIMUM_REQUIREMENTS }}
          PYTHONOPTIMIZE: ${{ inputs.PYTHONOPTIMIZE }}
        run: |
          pytest --doctest-plus --showlocals --pyargs skimage
