# Copied from NumPy https://github.com/numpy/numpy/pull/25894
# https://github.com/numpy/numpy/blob/d2d2c25fa81b47810f5cbd85ea6485eb3a3ffec3/.github/workflows/emscripten.yml
#

name: Test Emscripten/Pyodide build

on:
  pull_request:
    branches:
      - main
      - maintenance/**
  # TODO: remove after ready to merge
  push:
    # branches:
    #   - main
    #   - maintenance/**
  workflow_dispatch:

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-wasm-emscripten:
    name: Build scikit-image distribution for Pyodide
    runs-on: ubuntu-22.04
    # To enable this workflow on a fork, comment out:
    # if: github.repository == 'scikit-image/scikit-image'
    env:
      PYODIDE_VERSION: 0.25.0
      # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
      # The appropriate versions can be found in the Pyodide repodata.json
      # "info" field, or in Makefile.envs:
      # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
      PYTHON_VERSION: 3.11.3
      EMSCRIPTEN_VERSION: 3.1.46
      NODE_VERSION: 18
    steps:
      - name: Checkout scikit-image
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Emscripten toolchain
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      # We need to apply a patch to the Emscripten SDK to work around a bug in
      # the file system API. This patch is already applied in the Emscripten SDK
      # upstream, but we need to apply it here because we are using an older
      # version of the Emscripten SDK with Pyodide.
      - name: Apply necessary patch(es)
        run: |
          patch -d $EMSDK/upstream/emscripten/ -p1 < tools/emscripten/patches/0001-fix-npy-file-access.patch

      - name: Install pyodide-build
        run: pip install "pydantic<2" pyodide-build==${{ env.PYODIDE_VERSION }}

      - name: Build scikit-image for Pyodide
        run: |
          pyodide build

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # - name: Set up Pyodide virtual environment
      #   run: |
      #     pyodide venv .venv-pyodide
      #     source .venv-pyodide/bin/activate
      #     pip install dist/*.whl
      #     Remove pooch for now due to problems with downloading data files
      #     pip install matplotlib>=3.5 numpydoc>=1.5 pytest>=7.0 pytest-cov>=2.11.0 pytest-localserver pytest-faulthandler

      - name: Test scikit-image for Pyodide
        env:
          # Avoid using the default TkAgg backend, which requires GUI support
          MPLBACKEND: "Agg"
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate

          # pytest --doctest-modules --cov=skimage --showlocals --pyargs skimage

          # use the test.js script instead and don't run in venv
          npm install pyodide@${{ env.PYODIDE_VERSION }}
          node tools/emscripten/pytest_scikit_image_pyodide.js --pyargs skimage
