name: Milestone

on:
  push:
    branches:
      - "main"

permissions: {}

jobs:
  milestone_pr:
    name: attach to PR
    if: github.repository == 'scikit-image/scikit-image'
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: read

    steps:
      - uses: scientific-python/attach-next-milestone-action@806bd518fa2d47c076046246efcbca38a829d53b
        with:
          token: ${{ github.token }}
          force: true
