name: Run tests identified via dependency analysis

on: [pull_request]

permissions:
  contents: read

jobs:
  test_skimage_autodetect:
    name: macos-auto-cp${{ matrix.python-version }}
    runs-on: macos-13

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        OPTIONAL_DEPS: [1]

    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
      CPPFLAGS: "-Xpreprocessor -fopenmp"
      CFLAGS: "-Wno-implicit-function-declaration -I/usr/local/opt/libomp/include"
      CXXFLAGS: "-I/usr/local/opt/libomp/include"
      LDFLAGS: "-Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"

    steps:
      - name: Checkout scikit-image
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: OSX configuration
        run: |
          # OpenMP is not present on macOS by default
          brew install libomp

      - name: Install build dependencies
        run: |
          source .github/scripts/setup-build-env.sh

      - name: Build
        run: |
          spin build

      - name: Install test dependencies
        env:
          OPTIONAL_DEPS: ${{ matrix.OPTIONAL_DEPS }}
        run: |
          source .github/scripts/setup-test-env.sh

      - name: Run tests (dependency analysis)
        run: |
          spin test --detect-dependencies -- --config-file ${{ github.workspace }}
